src/objects/LAB_Mo_Tester_1__c.object
<CustomObject>
    <label>Mo Tester 1</label>
    <nameField>
        <label>Mo Tester 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mo Tester 1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LAB_MT1_Child_1__c.object
<CustomObject>
    <fields>
        <fullName>LAB_Mo_Tester_1__c</fullName>
        <label>Mo Tester 1</label>
        <referenceTo>LAB_Mo_Tester_1__c</referenceTo>
        <relationshipLabel>MT1 Child1s</relationshipLabel>
        <relationshipName>MT1_Child1s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MT1 Child 1</label>
    <nameField>
        <label>MT1 Child 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MT1 Child1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LAB_MT1_Grandchild_1__c.object
<CustomObject>
    <fields>
        <fullName>LAB_MT1_Child_1__c</fullName>
        <label>MT1 Child 1</label>
        <referenceTo>LAB_MT1_Child_1__c</referenceTo>
        <relationshipLabel>MT1 Grandchildren 1</relationshipLabel>
        <relationshipName>MT1_Grandchildren_1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MT1 Grandchild 1</label>
    <nameField>
        <label>MT1 Grandchild 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MT1 Grandchildren 1</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LAB_CreateDataHelper.cls
public with sharing class LAB_CreateDataHelper {
	
    public LAB_Mo_Tester_1__c moTester1 {get; set;}
    
    public LAB_CreateDataHelper() {}
    
    public LAB_CreateDataHelper(ApexPages.StandardController controller) {
    	this.moTester1 = (LAB_Mo_Tester_1__c) controller.getRecord(); 
    }
    
    public LAB_CreateDataHelper(ApexPages.StandardSetController setController) {
        
    }
    
    public PageReference createMoTester1() {
        SmartFactory.FillAllFields = true;
        LAB_Mo_Tester_1__c t = (LAB_Mo_Tester_1__c) SmartFactory.createSObject('LAB_Mo_Tester_1__c');
        insert t;
    	return new PageReference('/'+t.id);
    }
    
    public PageReference createManyMoTester1() {
        SmartFactory.FillAllFields = true;
        List<SObject> sobjects = SmartFactory.createSObjectList('LAB_Mo_Tester_1__c', false, 50);
        insert sobjects;
        return new PageReference('/' + LAB_Mo_Tester_1__c.sObjectType.getDescribe().getKeyPrefix());
    }
    
    public PageReference deleteAll() {
        List<LAB_Mo_Tester_1__c> mos = [Select Id From LAB_MO_Tester_1__c LIMIT 10000];
        delete mos;
        return new PageReference('/' + LAB_Mo_Tester_1__c.sObjectType.getDescribe().getKeyPrefix());
    }        
    
    public PageReference create3MT1WithChildrenAndGrandChildren() {
        //MT1
        SmartFactory.FillAllFields = true;
        List<SObject> mt1 = SmartFactory.createSObjectList('LAB_Mo_Tester_1__c', false, 3);
        insert mt1;
        
        //Children
        List<SObject> mt1c1 = new List<SObject>();
        for (Sobject current : mt1) {
	        List<SObject> children = SmartFactory.createSObjectList('LAB_MT1_Child_1__c', false, 3);
            for (SObject currentChild : children) {
                currentChild.put('LAB_Mo_Tester_1__c', current.get('id'));
            }
            mt1c1.addAll(children);
        }
        insert mt1c1;
        
        //Grandchildren
     	List<SObject> mt1gc1 = new List<SObject>();
        for (SObject currentChild : mt1c1) {
	        List<SObject> grandchildren = SmartFactory.createSObjectList('LAB_MT1_Grandchild_1__c', false, 3);
            for (SObject currentGrandchild : grandchildren) {
                currentGrandchild.put('LAB_MT1_Child_1__c', currentChild.get('Id'));
            }
            mt1gc1.addAll(grandChildren);
        }
        
        insert(mt1gc1);
        
        return new PageReference('/' + LAB_Mo_Tester_1__c.sObjectType.getDescribe().getKeyPrefix());
    }
    

}